INSERT INTO public.publications (title,publication_date,author,info_1,info_2,"uuid","content") VALUES
	 ('Poulet rôti aux herbes','2024-03-11 15:30:00','chefCook22',45,2,'4aeb3223-7990-479a-b154-861c2759a34c',' ## Ingrédients :\n- Poulet\n- Herbes\n- Sel\n- Poivre\n\n## Préparation :\n1. Assaisonner le poulet.\n2. Enfourner pendant 45 minutes.\n3. Déguster.\n'),
	 ('Tarte aux pommes caramélisées','2024-03-10 14:45:00','recipeMaster',30,6,'f535393e-d91a-451b-b144-fe054be1771d','## Ingrédients :\n- Pommes\n- Pâte brisée\n- Sucre\n- Beurre\n\n## Préparation :\n1. Préparer les pommes.\n2. Réaliser la pâte.\n3. Caraméliser les pommes.\n4. Monter la tarte.\n5. Enfourner pendant 30 minutes.\n6. Laisser refroidir avant de servir.\n'),
	 ('Risotto aux champignons','2024-03-09 12:20:00','kitchenGuru',40,3,'74bb74e6-ab2c-4b06-ae8c-7007ce5f8e92','## Ingrédients :\n- Riz\n- Champignons\n- Bouillon\n- Vin blanc\n\n## Préparation :\n1. Faire revenir les champignons.\n2. Ajouter le riz et le vin blanc.\n3. Ajouter progressivement le bouillon.\n4. Assaisonner.\n5. Servir chaud.\n'),
	 ('Gâteau au chocolat fondant','2024-03-08 18:00:00','cookingWizard',50,8,'ea29b205-75d9-4084-b10a-c3e044018a07','## Ingrédients :\n- Chocolat\n- Beurre\n- Oeufs\n- Sucre\n\n## Préparation :\n1. Faire fondre le chocolat et le beurre.\n2. Mélanger les œufs et le sucre.\n3. Incorporer le chocolat fondu.\n4. Enfourner pendant 50 minutes.\n5. Laisser refroidir avant de démouler.\n'),
	 ('Salade César','2024-03-07 11:10:00','foodieExpert',15,1,'7564ccd7-5af8-4347-9475-079af0b744a8','## Ingrédients :\n- Laitue romaine\n- Croûtons\n- Parmesan\n- Sauce César\n\n## Préparation :\n1. Préparer la sauce.\n2. Mélanger la laitue, les croûtons et le parmesan.\n3. Ajouter la sauce.\n4. Déguster.\n'),
	 ('Recette de lasagnes','2024-03-12 10:00:00','user123',60,4,'371cfc20-44b2-4d98-bda2-475bfcee70af','# Délicieuses Lasagnes\n\n## Ingrédients :\n- Pâtes\n- Viande hachée\n- Sauce tomate\n- Fromage râpé\n\n## Préparation :\n1. Faire cuire les pâtes dans une grande casserole d''''eau bouillante salée jusqu''''à ce qu''''elles soient al dente. Égoutter et réserver.\n2. Faire revenir la viande hachée dans une poêle jusqu''''à ce qu''''elle soit bien cuite.\n3. Ajouter la sauce tomate à la viande hachée et laisser mijoter pendant quelques minutes.\n4. Dans un plat à gratin, étaler une fine couche de sauce tomate.\n5. Disposer une couche de pâtes au fond du plat.\n6. Verser une couche de sauce tomate sur les pâtes.\n7. Saupoudrer de fromage râpé.\n8. Répéter les étapes 5 à 7 pour créer plusieurs couches de pâtes, sauce et fromage.\n9. Terminer par une couche de fromage râpé sur le dessus.\n10. Couvrir le plat de papier aluminium et enfourner à 180°C pendant 25 minutes.\n11. Retirer le papier aluminium et poursuivre la cuisson pendant 10 minutes, jusqu''''à ce que le fromage soit doré et bouillonne.\n12. Laisser reposer pendant quelques minutes avant de servir.\n\nPour plus de recettes délicieuses, consultez [notre site web](https://www.recettes-lasagnes.com).'),
	 ('Pizza maison','2024-03-06 16:20:00','pizzaLover',30,4,'c9df34de-27c9-4312-b93a-1f61e0191fae','## Ingrédients :\n- Pâte à pizza\n- Sauce tomate\n- Fromage\n- Garniture au choix\n\n## Préparation :\n1. Étaler la pâte.\n2. Étaler la sauce tomate.\n3. Ajouter le fromage et la garniture.\n4. Enfourner pendant 30 minutes.\n5. Déguster chaud.\n'),
	 ('Pâtes à la carbonara','2024-03-05 09:30:00','pastaFanatic',25,2,'a8894df1-41ee-4a97-9bc5-01d7906cebe5','## Ingrédients :\n- Spaghetti\n- Lardons\n- Œufs\n- Parmesan\n- Crème fraîche\n\n## Préparation :\n1. Cuire les pâtes.\n2. Faire revenir les lardons.\n3. Mélanger les œufs et le parmesan.\n4. Incorporer la crème fraîche.\n5. Mélanger avec les pâtes cuites.\n6. Servir chaud.\n'),
	 ('Soupe de potiron','2024-03-04 13:15:00','soupConnoisseur',20,5,'e8d23ee8-5f79-4e95-a0ad-421cd0747916','## Ingrédients :\n- Potiron\n- Oignon\n- Bouillon de légumes\n- Crème fraîche\n\n## Préparation :\n1. Faire revenir l''oignon.\n2. Ajouter le potiron et le bouillon.\n3. Laisser mijoter jusqu\''à ce que le potiron soit tendre.\n4. Mixer la soupe.\n5. Ajouter la crème fraîche.\n6. Assaisonner selon votre goût.\n7. Servir chaud.\n'),
	 ('Tartelette aux fraises','2024-03-03 17:45:00','dessertEnthusiast',35,6,'347c949f-de86-4bc2-bfc9-7268a9e6f4ad','## Ingrédients :\n- Pâte sablée\n- Fraises\n- Crème pâtissière\n- Gelée de fruits rouges\n\n## Préparation :\n1. Préchauffez le four à 180°C.\n2. Foncer les moules à tartelette avec la pâte sablée.\n3. Piquez le fond avec une fourchette et enfournez pendant 15 minutes.\n4. Pendant ce temps, préparez la crème pâtissière et laissez-la refroidir.\n5. Lavez et équeutez les fraises, puis coupez-les en fines tranches.\n6. Une fois les fonds de tartelettes cuits et refroidis, étalez la crème pâtissière dessus.\n7. Disposez les tranches de fraises sur la crème de manière esthétique.\n8. Chauffez la gelée de fruits rouges et nappez-en légèrement les fraises pour les faire briller.\n9. Laissez refroidir au réfrigérateur pendant au moins 1 heure avant de servir.');
